import Head from "next/head"
import { Parallax, ParallaxLayer } from "@react-spring/parallax"
import { NextURL } from "next/dist/server/web/next-url"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img className="bgArt" src="/images/bg.png" alt="ai generated background art"/>
        
        {/* <Parallax className="content" pages={3}
        >
          <ParallaxLayer
            offset={0}
            style={{
              backgroundImage: `url(${'/images/bg1.png'})`,
              backgroundSize: 'cover'
            }}
          />
          <ParallaxLayer
            offset={0}
            speed={1}
          >
            <h1>Jack Youkstetter</h1>
          </ParallaxLayer>
          <ParallaxLayer
            offset={1}
            speed={1}
          >
            <h2>Full Stack Dev</h2>
          </ParallaxLayer>

            
        </Parallax> */}
      </main>
    </>
  )
}
